const CONFIG = {
    titleWeb: "Tích Kim's World",
    introTitle: 'Nguyễn Huế Anh <3',
    introDesc: `Chỉ mong hoa luôn nở,
    Người thì luôn ở đây, 
    Cả đời làm trỷ,
    Vĩnh viễn không chia lìa`,
    btnIntro: '^^HoHo^^',
    title: 'Hãy để tớ che chở, bảo vệ cậu đến dương vô cùng nhá 🥰',
    desc: 'Bởi vì tớ thương cậu  ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Mình cắn cậu đấy ',
    question: 'Vậy Huế Anh cho tớ biết lí do đi nào <3',
    btnReply: 'Gửi cho iuiu <3',
    reply: 'Vì bạn là số một, bạn là siêu sao, bạn là đỉm 1000000000',
    mess: 'Ây da mình biết mà 🥰. Thương bạn nhiều nhiều 😘😘',
    messDesc: 'Mình đánh dấu chủ quyền ròi đấy nhá',
    btnAccept: 'Oki lun :))',
    messLink: 'https://www.facebook.com/luongtichkim' //link mess của các bạn. VD: https://m.me/nam.nodemy
}
